"""
Module contains the DataElementFormat class and DATA_ELEMENT_FORMAT dictionary
"""
from dataclasses import dataclass

@dataclass
class DataElementFormat:
    """
    Describes the data element format
    """
    content_type: str
    is_fixed: bool
    field_max_length: int
    meaning: str

DATA_ELEMENT_FORMAT = {
    1:   DataElementFormat('b',     True,  16,  'Bitmap'),
    2:   DataElementFormat('n',     False, 19,  'Primary account number (PAN)'),
    3:   DataElementFormat('n',     True,  6,   'Processing code'),
    4:   DataElementFormat('n',     True,  12,  'Amount, transaction'),
    5:   DataElementFormat('n',     True,  12,  'Amount, settlement'),
    6:   DataElementFormat('n',     True,  12,  'Amount, cardholder billing'),
    7:   DataElementFormat('n',     True,  10,  'Transmission date and time (MMDDhhmmss)'),
    8:   DataElementFormat('n',     True,  8,   'Amount, cardholder billing fee'),
    9:   DataElementFormat('n',     True,  8,   'Conversion rate, settlement'),
    10:  DataElementFormat('n',     True,  8,   'Conversion rate, cardholder billing'),
    11:  DataElementFormat('n',     True,  6,   'System trace audit number (STAN)'),
    12:  DataElementFormat('n',     True,  6,   'Local transaction time (hhmmss)'),
    13:  DataElementFormat('n',     True,  4,   'Local transaction date (MMDD)'),
    14:  DataElementFormat('n',     True,  4,   'Expiration date (YYMM)'),
    15:  DataElementFormat('n',     True,  4,   'Settlement date'),
    16:  DataElementFormat('n',     True,  4,   'Currency conversion date'),
    17:  DataElementFormat('n',     True,  4,   'Capture date'),
    18:  DataElementFormat('n',     True,  4,   'Merchant type / category code (MCC)'),
    19:  DataElementFormat('n',     True,  3,   'Acquiring institution country code'),
    20:  DataElementFormat('n',     True,  3,   'PAN extended country code'),
    21:  DataElementFormat('n',     True,  3,   'Forwarding institution country code'),
    22:  DataElementFormat('n',     True,  3,   'Point of service entry mode'),
    23:  DataElementFormat('n',     True,  3,   'Application PAN sequence number'),
    24:  DataElementFormat('n',     True,  3,   'Function code / network international identifier (NII)'),
    25:  DataElementFormat('n',     True,  2,   'Point of service condition code'),
    26:  DataElementFormat('n',     True,  2,   'Point of service capture code'),
    27:  DataElementFormat('n',     True,  1,   'Authorizing identification response length'),
    28:  DataElementFormat('x+n',   True,  8,   'Amount, transaction fee'),
    29:  DataElementFormat('x+n',   True,  8,   'Amount, settlement fee'),
    30:  DataElementFormat('x+n',   True,  8,   'Amount, transaction processing fee'),
    31:  DataElementFormat('x+n',   True,  8,   'Amount, settlement processing fee'),
    32:  DataElementFormat('n',     False, 11,  'Acquiring institution identification code'),
    33:  DataElementFormat('n',     False, 11,  'Forwarding institution identification code'),
    34:  DataElementFormat('ns',    False, 28,  'Primary account number, extended'),
    35:  DataElementFormat('z',     False, 37,  'Track 2 data'),
    36:  DataElementFormat('n',     False, 104, 'Track 3 data'),
    37:  DataElementFormat('an',    True,  12,  'Retrieval reference number'),
    38:  DataElementFormat('an',    True,  6,   'Authorization identification response (approval code)'),
    39:  DataElementFormat('an',    True,  2,   'Response code'),
    40:  DataElementFormat('an',    True,  3,   'Service restriction code'),
    41:  DataElementFormat('ans',   True,  8,   'Card acceptor terminal identification'),
    42:  DataElementFormat('ans',   True,  15,  'Card acceptor identification code'),
    43:  DataElementFormat('ans',   True,  40,  'Card acceptor name / location'),
    44:  DataElementFormat('an',    False, 25,  'Additional response data'),
    45:  DataElementFormat('an',    False, 76,  'Track 1 data'),
    46:  DataElementFormat('an',    False, 999, 'Additional data (ISO)'),
    47:  DataElementFormat('an',    False, 999, 'Additional data (national)'),
    48:  DataElementFormat('an',    False, 999, 'Additional data (private)'),
    49:  DataElementFormat('a or n',True,  3,   'Currency code, transaction'),
    50:  DataElementFormat('a or n',True,  3,   'Currency code, settlement'),
    51:  DataElementFormat('a or n',True,  3,   'Currency code, cardholder billing'),

    # field_max_length should be 64, but since the implementation reads bytes
    # and 64 bits = 8 bytes, the change was made
    52:  DataElementFormat('b',     True,  8,  'Personal identification number (PIN) data'),
    53:  DataElementFormat('n',     True,  16,  'Security related control information'),
    54:  DataElementFormat('an',    False, 120, 'Additional amounts'),
    55:  DataElementFormat('ans',   False, 999, 'ICC data / EMV data (TLV)'),
    56:  DataElementFormat('ans',   False, 999, 'Reserved (ISO)'),
    57:  DataElementFormat('ans',   False, 999, 'Reserved (national)'),
    58:  DataElementFormat('ans',   False, 999, 'Reserved (national)'),
    59:  DataElementFormat('ans',   False, 999, 'Reserved (national)'),
    60:  DataElementFormat('ans',   False, 999, 'Reserved (national)'),
    61:  DataElementFormat('ans',   False, 999, 'Reserved (private)'),
    62:  DataElementFormat('ans',   False, 999, 'Reserved (private)'),
    63:  DataElementFormat('ans',   False, 999, 'Reserved (private)'),

    # # same reason as DE 52
    64:  DataElementFormat('b',     True,  8,  'Message authentication code (MAC)'),
    65:  DataElementFormat('b',     True,  1,   'Extended bitmap indicator'),
    66:  DataElementFormat('n',     True,  1,   'Settlement code'),
    67:  DataElementFormat('n',     True,  2,   'Extended payment code'),
    68:  DataElementFormat('n',     True,  3,   'Receiving institution country code'),
    69:  DataElementFormat('n',     True,  3,   'Settlement institution country code'),
    70:  DataElementFormat('n',     True,  3,   'Network management information code'),
    71:  DataElementFormat('n',     True,  4,   'Message number'),
    72:  DataElementFormat('n',     True,  4,   'Last message number'),
    73:  DataElementFormat('n',     True,  6,   'Action date (YYMMDD)'),
    74:  DataElementFormat('n',     True,  10,  'Number of credits'),
    75:  DataElementFormat('n',     True,  10,  'Credits, reversal number'),
    76:  DataElementFormat('n',     True,  10,  'Number of debits'),
    77:  DataElementFormat('n',     True,  10,  'Debits, reversal number'),
    78:  DataElementFormat('n',     True,  10,  'Transfer number'),
    79:  DataElementFormat('n',     True,  10,  'Transfer, reversal number'),
    80:  DataElementFormat('n',     True,  10,  'Number of inquiries'),
    81:  DataElementFormat('n',     True,  10,  'Number of authorizations'),
    82:  DataElementFormat('n',     True,  12,  'Credits, processing fee amount'),
    83:  DataElementFormat('n',     True,  12,  'Credits, transaction fee amount'),
    84:  DataElementFormat('n',     True,  12,  'Debits, processing fee amount'),
    85:  DataElementFormat('n',     True,  12,  'Debits, transaction fee amount'),
    86:  DataElementFormat('n',     True,  16,  'Total amount of credits'),
    87:  DataElementFormat('n',     True,  16,  'Credits, reversal amount'),
    88:  DataElementFormat('n',     True,  16,  'Total amount of debits'),
    89:  DataElementFormat('n',     True,  16,  'Debits, reversal amount'),
    90:  DataElementFormat('n',     True,  42,  'Original data elements'),
    91:  DataElementFormat('an',    True,  1,   'File update code'),
    92:  DataElementFormat('an',    True,  2,   'File security code'),
    93:  DataElementFormat('an',    True,  5,   'Response indicator'),
    94:  DataElementFormat('an',    True,  7,   'Service indicator'),
    95:  DataElementFormat('an',    True,  42,  'Replacement amounts'),

    # same reason as DE 52 and 64
    96:  DataElementFormat('b',     True,  8,  'Message security code'),
    97:  DataElementFormat('x+n',   True,  16,  'Net settlement amount'),
    98:  DataElementFormat('ans',   True,  25,  'Payee'),
    99:  DataElementFormat('n',     False, 11,  'Settlement institution identification code'),
    100: DataElementFormat('n',     False, 11,  'Receiving institution identification code'),
    101: DataElementFormat('ans',   False, 17,  'File name'),
    102: DataElementFormat('ans',   False, 28,  'Account identification 1'),
    103: DataElementFormat('ans',   False, 28,  'Account identification 2'),
    104: DataElementFormat('ans',   False, 100, 'Transaction description'),
    105: DataElementFormat('ans',   False, 999, 'Reserved for ISO use'),
    106: DataElementFormat('ans',   False, 999, 'Reserved for ISO use'),
    107: DataElementFormat('ans',   False, 999, 'Reserved for ISO use'),
    108: DataElementFormat('ans',   False, 999, 'Reserved for ISO use'),
    109: DataElementFormat('ans',   False, 999, 'Reserved for ISO use'),
    110: DataElementFormat('ans',   False, 999, 'Reserved for ISO use'),
    111: DataElementFormat('ans',   False, 999, 'Reserved for ISO use'),
    112: DataElementFormat('ans',   False, 999, 'Reserved for national use'),
    113: DataElementFormat('ans',   False, 999, 'Reserved for national use'),
    114: DataElementFormat('ans',   False, 999, 'Reserved for national use'),
    115: DataElementFormat('ans',   False, 999, 'Reserved for national use'),
    116: DataElementFormat('ans',   False, 999, 'Reserved for national use'),
    117: DataElementFormat('ans',   False, 999, 'Reserved for national use'),
    118: DataElementFormat('ans',   False, 999, 'Reserved for national use'),
    119: DataElementFormat('ans',   False, 999, 'Reserved for national use'),
    120: DataElementFormat('ans',   False, 999, 'Reserved for private use'),
    121: DataElementFormat('ans',   False, 999, 'Reserved for private use'),
    122: DataElementFormat('ans',   False, 999, 'Reserved for private use'),
    123: DataElementFormat('ans',   False, 999, 'Reserved for private use'),
    124: DataElementFormat('ans',   False, 999, 'Reserved for private use'),
    125: DataElementFormat('ans',   False, 999, 'Reserved for private use'),
    126: DataElementFormat('ans',   False, 999, 'Reserved for private use'),
    127: DataElementFormat('ans',   False, 999, 'Reserved for private use'),

    # same reason as DE 52, 64 and 96
    128: DataElementFormat('b',     True,  8,  'Message authentication code'),
}
